settings:
  data_cache_dir: /e/project1/crescendo/reim1/ntv3_data
  species_token_budgets_file: /e/project1/crescendo/reim1/ntv3_benchmark/configs/species_token_budgets.yaml
  epochs: 10
  window_size: 1024
  training_fraction: 0.1
  validation_fraction: 0.1
  seed: 42

models_to_test:
    - name: InstaDeepAI/NTv3_100M_pre
      type: huggingface
      checkpoint: InstaDeepAI/NTv3_100M_pre
      hidden_dim: 768
      window_size: 32768
      batch_size: 16

tasks:
  Regression_all:
    type: regression
    species: human
    keep_target_center_fraction: 0.375
    #bigwig_ids:
    force_recompute: true
    learning_rate: 1e-4

  Exon:
    type: classification
    species: human
    bed_ids: ["exon"]
    keep_target_center_fraction: 0.375
    force_recompute: true
    learning_rate: 1e-5

  Intron:
    type: classification
    species: human
    bed_ids: ["intron"]
    keep_target_center_fraction: 0.375
    force_recompute: true
    learning_rate: 1e-5

  Splice_acceptor:
    type: classification
    species: human
    bed_ids: ["splice_acceptor"]
    keep_target_center_fraction: 0.375
    force_recompute: true
    learning_rate: 1e-5

  Start_codon:
    type: classification
    species: human
    bed_ids: ["start_codon"]
    keep_target_center_fraction: 0.375
    force_recompute: true
    learning_rate: 1e-5


# ~/.local/bin/uv run python /e/project1/crescendo/reim1/ntv3_benchmark/run_benchmark.py